apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-demo-
spec:
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  templates:
  - name: main
    steps:
    - - name: setup
        template: setup
    - - name: do
        template: do
  - name: setup
    container:
      image: lunatech.com/argo-demo-setup:0.0.1
      volumeMounts:
      - name: workdir
        mountPath: /app/data
  - name: do
    container:
      image: lunatech.com/argo-demo-do:0.0.1
      volumeMounts:
      - name: workdir
        mountPath: /app/data
