apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: argo-demo-
spec:
  entrypoint: main
  arguments:
    parameters:
    - name: logfile
      value: "/app/data/log.txt"
  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
  templates:
  - name: main
    steps:
    - - name: setup
        template: setup
    - - name: do
        template: do
  - name: setup
    container:
      image: docker.pkg.github.com/lunatech-labs/lunatech-argo-demo/argo-demo-setup:0.0.1
      volumeMounts:
      - name: workdir
        mountPath: /app/data
      env:
      - name: LOGFILE
        value: "{{workflow.parameters.logfile}}"
  - name: do
    container:
      image: docker.pkg.github.com/lunatech-labs/lunatech-argo-demo/argo-demo-do:0.0.1
      volumeMounts:
      - name: workdir
        mountPath: /app/data
      env:
      - name: LOGFILE
        value: "{{workflow.parameters.logfile}}"
