---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: native-k8s-pv-claim
  namespace: demo
spec:
  storageClassName: hostPath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
