name: Build and release
on: [push]
jobs:
  Build binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - run: go version
      - name: Build setup
        run: cd setup && go build
      - name: Build do
        run: cd do && go build
